version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: multi-agent-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/backend/src:ro
      - ./backend/prompts:/app/backend/prompts:ro
    networks:
      - multi-agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit UI service
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: multi-agent-ui
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./ui/src:/app/ui/src:ro
    networks:
      - multi-agent-network
    restart: unless-stopped

networks:
  multi-agent-network:
    driver: bridge

# Example usage:
# Start backend only: docker-compose up backend
# Start both services: docker-compose up
# Development with hot reload: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
